export enum Character {
    Geppetto = 'geppetto', 
}

export enum Emotion {
    Admiring = 'admiring', Angry = 'angry', 
    Annoyed = 'annoyed', Aroused = 'aroused',
    BlushingShyly = 'blushing shyly', Bored = 'bored',
    ChildlikeWhining = 'childlike whining', Comforted = 'comforted',
    Confused = 'confused', Contemptuous = 'contemptuous',
    Coughing = 'coughing', CrazySmiling = 'crazy smiling',
    CryingWithEyesClosed = 'crying with eyes closed', CryingWithEyesOpen = 'crying with eyes open',
    Curious = 'curious', Dazed = 'dazed',
    Depressed = 'depressed', Determined = 'determined',
    Disappointed = 'disappointed', Disgusted = 'disgusted',
    Embarrassed = 'embarrassed', EvilSmiling = 'evil smiling',
    Excited = 'excited', Exhausted = 'exhausted',
    FidgetingShyly = 'fidgeting shyly', Flustered = 'flustered',
    ForcedSmile = 'forced smile', FullFaceBlush = 'full-face blush',
    Giggling = 'giggling', Guilty = 'guilty',
    HappySmiling = 'happy smiling', Indifferent = 'indifferent',
    Jealous = 'jealous', Joyful = 'joyful',
    Laughing = 'laughing', LookingAwayShyly = 'looking away shyly',
    LoveStruck = 'lovestruck', Lustful = 'lustful',
    NervousPouting = 'nervous pouting', NervousSmiling = 'nervous smiling',
    Nervous = 'nervous', Neutral = 'neutral',
    PlayfulWinking = 'playful winking', Pleading = 'pleading',
    Pouting = 'pouting', Proud = 'proud',
    Relieved = 'relieved', Sad = 'sad',
    Scared = 'scared', SeductiveSmiling = 'seductive smiling',
    Serious = 'serious', Shocked = 'shocked',
    Sleepy = 'sleepy', Smiling = 'smiling',
    Smirking = 'smirking', Smug = 'smug',
    Sniggering = 'sniggering', Surprised = 'surprised',
    Suspicious = 'suspicious', Thinking = 'thinking',
    Worried = 'worried',
}