import React from 'react';
import ChatBar from './ChatBar';

const ResponseBox: React.FC = () => {
    return (
        <div className='response-box'>
            <div className='response-content'>
                response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box
                response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box
                response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box
                response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box response box
            </div>
            <ChatBar enable={true} />
        </div>
    );
}

export default ResponseBox;